name: action_on_push
on:
  push:
  branches:
      - main
        paths:
       - '*.py'
  status: {}
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created
  
