name: new_issue
on:
  push:
    paths:
    - '*.py'
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: push
        run: |
          curl -X POST --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/avivel97/linux-git1/issues -d '{"title":"test issue from datamove", "body": "yep, just a test!"}'
          ${{ github.event.push.url }}/merge \
          -d '{"commit_title":"redactered python-file pr ${{github.event.push.number }} for ${{ github.event.push.user.login }}" }'

