name: action_on_push
on:
  push:
   paths:
          - '*.py'
  status: {}
  page_build: "Thanks for a p—Éthon script edit"
  release:
    types: # This configuration does not affect the page_build event above
      - created
  
